ue_type: 'mc_maha'
dropout_type: 'MC'
dropout_subs: 'all'
inference_prob: 0.1
committee_size: 20
use_cache: False
eval_passes: False
calibrate: False
use_spectralnorm: False
use_selective: False
lamb: 0.01
margin: 0.05
lamb_intra: 0.01
reg_type: 'reg-curr'