ue_type: 'sngp'
dropout_subs: ''
dropout_type: ''
committee_size: 20
use_cache: True
eval_passes: False
calibrate: False
use_spectralnorm: False
use_selective: False
lamb: 0.01
margin: 0.05
lamb_intra: 0.01
reg_type: 'raw'
sngp:
    ridge_factor: 0.001
    gp_hidden_dim: 2048
    momentum: 0.999
    use_layer_norm: True