ue_type: 'sto'
dropout_type: 'sto'
inference_prob: 0.0
committee_size: 20
dropout_subs: 'last'
use_cache: True
eval_passes: False
calibrate: False
use_ood_sampling: False
use_selective: False
lamb: 0.01
reg_type: 'reg-curr'
use_sto: True
hierarchial: True
sto_layer: 'all'
num_centroids: 16
tau_1: 1
tau_2: 20