cd ../../src
# Script for training all models on MRPC, COLA, SST2-10% - for old version of metric loss, with 2 params.
# train - metric loss, no SN
#HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=1.0 +ue.margin\=2.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric training.learning_rate\=6e-5 training.num_train_epochs\=6 training.per_device_train_batch_size\=8 +training.weight_decay\=0.1' task_configs=mrpc.yaml output_dir=../workdir/run_train_models/metric_opt_electra_fix6/mrpc/metric

#HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.005 +ue.margin\=5.0 +ue.lamb_intra\=1.0 ue.reg_type\=metric training.learning_rate\=9e-6 training.num_train_epochs\=15 training.per_device_train_batch_size\=32 +training.weight_decay\=1e-1' task_configs=cola.yaml output_dir=../workdir/run_train_models/metric_opt_electra/cola/metric
#HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.008 +ue.margin\=0.025 +ue.lamb_intra\=1.0 ue.reg_type\=metric training.learning_rate\=2e-5 training.num_train_epochs\=7 training.per_device_train_batch_size\=32 +training.weight_decay\=0.1' task_configs=sst2.yaml output_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric

# train - metric loss, SN
#HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.008 +ue.margin\=0.25 +ue.lamb_intra\=1.0 ue.reg_type\=metric +ue.use_spectralnorm\=True spectralnorm_layer\=last training.learning_rate\=1e-4 training.num_train_epochs\=15 training.per_device_train_batch_size\=64 +training.weight_decay\=0.1' task_configs=mrpc.yaml output_dir=../workdir/run_train_models/metric_opt_electra/mrpc/metric_sn
#HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.003 +ue.margin\=0.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric +ue.use_spectralnorm\=True spectralnorm_layer\=last training.learning_rate\=2e-5 training.num_train_epochs\=14 training.per_device_train_batch_size\=32 +training.weight_decay\=0.01' task_configs=cola.yaml output_dir=../workdir/run_train_models/metric_opt_electra/cola/metric_sn
#HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.02 +ue.margin\=0.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric +ue.use_spectralnorm\=True spectralnorm_layer\=last training.learning_rate\=7e-6 training.num_train_epochs\=12 training.per_device_train_batch_size\=8 +training.weight_decay\=0.1' task_configs=sst2.yaml output_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric_sn


# Estimate
# TODO - 3 datasets, last|all|DPP|DPP OOD|mc_maha
# Last
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/mrpc.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra_fix6/mrpc/metric/models/mrpc/ args='ue\=mc do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last  ue.lamb\=1.0 +ue.margin\=2.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/last'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/cola.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/cola/metric/models/cola/ args='ue\=mc do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.005 +ue.margin\=5.0 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/last'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/sst2.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric/models/sst2/ args='ue\=mc do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last  ue.lamb\=0.008 +ue.margin\=0.025 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/last'

# all
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/mrpc.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra_fix6/mrpc/metric/models/mrpc/ args='ue\=mc do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=all  ue.lamb\=1.0 +ue.margin\=2.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/all'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/cola.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/cola/metric/models/cola/ args='ue\=mc do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=all ue.lamb\=0.005 +ue.margin\=5.0 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/all'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/sst2.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric/models/sst2/ args='ue\=mc do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=all  ue.lamb\=0.008 +ue.margin\=0.025 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/all'

# DPP 2
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/mrpc.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra_fix6/mrpc/metric/models/mrpc/ args='ue\=mc-dpp do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last  ue.lamb\=1.0 +ue.margin\=2.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.max_frac\=0.3' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/dpp'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/cola.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/cola/metric/models/cola/ args='ue\=mc-dpp do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.005 +ue.margin\=5.0 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.max_frac\=0.6' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/dpp'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/sst2.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric/models/sst2/ args='ue\=mc-dpp do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last  ue.lamb\=0.008 +ue.margin\=0.025 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.max_frac\=0.4' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/dpp'

# DPP with OOD
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/mrpc.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra_fix6/mrpc/metric/models/mrpc/ args='ue\=mc-dpp do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=1.0 +ue.margin\=2.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.dropout.use_ood_sampling\=True ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.max_frac\=0.6' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/dpp_with_ood'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/cola.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/cola/metric/models/cola/ args='ue\=mc-dpp do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.005 +ue.margin\=5.0 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.dropout.use_ood_sampling\=True ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.max_frac\=0.3' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/dpp_with_ood'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/sst2.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric/models/sst2/ args='ue\=mc-dpp do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.008 +ue.margin\=0.025 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.dropout.use_ood_sampling\=True ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.max_frac\=0.6' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/dpp_with_ood'

# MC maha
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/mrpc.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra_fix6/mrpc/metric/models/mrpc/ args='ue\=mc_mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.lamb\=1.0 +ue.margin\=2.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/maha_mc'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/cola.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/cola/metric/models/cola/ args='ue\=mc_mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.lamb\=0.005 +ue.margin\=5.0 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/maha_mc'
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/sst2.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric/models/sst2/ args='ue\=mc_mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.lamb\=0.008 +ue.margin\=0.025 +ue.lamb_intra\=1.0 ue.reg_type\=metric' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/maha_mc'


# Now estimate mc_maha with SN model
#HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/mrpc.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/mrpc/metric_sn/models/mrpc/ args='ue\=mc_mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.lamb\=0.008 +ue.margin\=0.25 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.use_spectralnorm\=True spectralnorm_layer\=last' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/mrpc/maha_sn_mc'
HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/cola.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/cola/metric_sn/models/cola/ args='ue\=mc_mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.lamb\=0.003 +ue.margin\=0.5 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.use_spectralnorm\=True spectralnorm_layer\=last' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/maha_sn_mc'
HYDRA_CONFIG_PATH=../configs/run_glue_for_model_series.yaml python ./run_glue_for_model_series.py cuda_devices=[1,2,3] seeds=[23419,705525,4837,10671619,1084218,43] config_path=../configs/sst2.yaml model_series_dir=../workdir/run_train_models/metric_opt_electra/sst2/metric_sn/models/sst2/ args='ue\=mc_mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.lamb\=0.02 +ue.margin\=0.05 +ue.lamb_intra\=1.0 ue.reg_type\=metric ue.use_spectralnorm\=True spectralnorm_layer\=last' output_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/maha_sn_mc'



# Finally, calc metrics
# last
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/last/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra_fix6/mrpc/last'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/last/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/cola/last'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/last/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/sst2/last'
# all
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/all/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra_fix6/mrpc/all'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/all/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/cola/all'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/all/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/sst2/all'
# dpp2
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/dpp/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra_fix6/mrpc/dpp'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/dpp/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/cola/dpp'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/dpp/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/sst2/dpp'
# dpp with ood
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/dpp_with_ood/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra_fix6/mrpc/dpp_with_ood'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/dpp_with_ood/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/cola/dpp_with_ood'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/dpp_with_ood/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/sst2/dpp_with_ood'
# mc maha
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra_fix6/mrpc/maha_mc/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra_fix6/mrpc/maha_mc'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/maha_mc/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/cola/maha_mc'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/maha_mc/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/sst2/maha_mc'
# sn mc maha
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/mrpc/maha_sn_mc/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/mrpc/maha_sn_mc'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/cola/maha_sn_mc/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/cola/maha_sn_mc'
#HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/metric_opt_electra/sst2/maha_sn_mc/results' output_dir='../workdir/run_calc_ues_metrics/metric_opt_electra/sst2/maha_sn_mc'
