bash run_train_electra_models_sst2_dif_size.sh
bash run_train_electra_models_mrpc_dif_size.sh
bash run_train_electra_models_cola_dif_size.sh
bash run_eval_electra_models_sst2_det_best_dif_size.sh
bash run_eval_electra_models_mrpc_det_best_dif_size.sh
bash run_eval_electra_models_cola_det_best_dif_size.sh