# exit when any command fails
set -e
cd ../src

CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_sn/cola/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_sn/cola/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_sn/cola/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/cola/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/cola/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/cola.yaml python run_glue.py ue\=sngp do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/cola/sngp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=decomposing_md do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_sn/sst5/decomposing_md
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=nuq do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_sn/sst5/nuq
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mahalanobis do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=True data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_sn/sst5/mahalanobis
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/sst5/mc
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_metric_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_metric_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_metric_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=metric ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_metric_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_reg_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_reg_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_reg_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=True ue.reg_type\=reg-curr ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_reg_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='microsoft/deberta-base' output_dir=../workdir/run_tests/deberta_raw_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='roberta-base' output_dir=../workdir/run_tests/roberta_raw_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=mc-dpp ue.committee_size\=2 do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='distilbert-base-cased' output_dir=../workdir/run_tests/distilbert_raw_no_sn/sst5/mc-dpp
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/sst5.yaml python run_glue.py ue\=sngp do_ue_estimate\=True ue.use_selective\=False ue.reg_type\=raw ++ue.use_spectralnorm\=False data.validation_subsample\=0.0 data.subsample_perc\=0.02 training\=electra_base training.per_device_eval_batch_size\=32 model.model_name_or_path\='google/electra-base-discriminator' output_dir=../workdir/run_tests/electra_raw_no_sn/sst5/sngp