cd ../../src

# Raw models
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw' task_configs=mrpc.yaml output_dir=../workdir/run_train_models/distilbert_hypopt/raw/mrpc
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw' task_configs=cola.yaml output_dir=../workdir/run_train_models/distilbert_hypopt/raw/cola
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw' task_configs=sst2.yaml output_dir=../workdir/run_train_models/distilbert_hypopt/raw/sst2

HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_conll2003_with_hyp_search.py task_configs=conll2003.yaml args='do_ue_estimate\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1 +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw' seeds=[23419] cuda_devices=[0] output_dir='../workdir/run_train_models/distilbert_hypopt/raw/conll'

# Raw SN models
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=True spectralnorm_layer\=last' task_configs=mrpc.yaml output_dir=../workdir/run_train_models/distilbert_hypopt/raw_sn/mrpc
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=True spectralnorm_layer\=last' task_configs=cola.yaml output_dir=../workdir/run_train_models/distilbert_hypopt/raw_sn/cola
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=True spectralnorm_layer\=last' task_configs=sst2.yaml output_dir=../workdir/run_train_models/distilbert_hypopt/raw_sn/sst2

HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_conll2003_with_hyp_search.py task_configs=conll2003.yaml args='do_ue_estimate\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1 +training.save_strategy\=no model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=True spectralnorm_layer\=last' seeds=[23419] cuda_devices=[0] output_dir='../workdir/run_train_models/distilbert_hypopt/raw_sn/conll'
