cd ../../src

# Raw models
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue.py cuda_devices=[1] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw training.learning_rate\=7e-5 training.num_train_epochs\=6 training.per_device_train_batch_size\=32 +training.weight_decay\=0.0' task_configs=mrpc.yaml output_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue.py cuda_devices=[1] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw training.learning_rate\=7e-5 training.num_train_epochs\=6 training.per_device_train_batch_size\=32 +training.weight_decay\=0.0' task_configs=cola.yaml output_dir=../workdir/run_train_models/distilbert_raw/cola/0.0
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue.py cuda_devices=[1] seeds=[23419,705525,4837,10671619,1084218,43] args='ue\=mc do_ue_estimate\=False ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw training.learning_rate\=3e-5 training.num_train_epochs\=14 training.per_device_train_batch_size\=32 +training.weight_decay\=0.0' task_configs=sst2.yaml output_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_conll2003.py task_configs=conll2003.yaml args='do_ue_estimate\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1 model.model_name_or_path\=distilbert-base-cased ue.use_selective\=False ue.reg_type\=raw training.learning_rate\=3e-5 training.num_train_epochs\=15 training.per_device_train_batch_size\=4 +training.weight_decay\=0.1' seeds=[23419,705525,4837,10671619,1084218,43] cuda_devices=[1] output_dir='../workdir/run_train_models/distilbert_raw/conll2003/0.0'


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.3_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.3_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.4_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.4_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.5_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.5_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.6_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/mrpc.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.6_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/mrpc/0.0/models/mrpc
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.3_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.3_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.4_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.4_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.5_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.5_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.6_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/cola.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.6_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/cola/0.0/models/cola
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.3_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.3_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.4_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.4_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.5_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.5_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.6_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=50 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True' config_path=../configs/sst2.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.6_50/ model_series_dir=../workdir/run_train_models/distilbert_raw/sst2/0.0/models/sst2


HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.3_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.3 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.3_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.4_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.4 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.4_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.5_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.5 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.5_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.6_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003
HYDRA_CONFIG_PATH=../configs/run_tasks_for_model_series.yaml python run_tasks_for_model_series.py script=run_conll2003.py cuda_devices=[1] args='ue\=mc-dpp do_ue_estimate\=True +ue.use_spectralnorm\=False ue.calibrate\=True data.validation_subsample\=0.0 +data.eval_subsample\=0.2 ue.use_selective\=False training\=electra_base ue.dropout.is_reused_mask\=True ue.dropout.max_frac\=0.6 ue.dropout.committee_size\=20 ue.committee_size\=100 ue.dropout.use_ood_sampling\=True data.subsample_perc_val\=0.1 data.subsample_perc\=0.1' config_path=../configs/conll2003.yaml script=run_glue_dpp_hp.py output_dir=../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.6_20/ model_series_dir=../workdir/run_train_models/distilbert_raw/conll2003/0.0/models/conll2003




# Finally, calc metrics
# last
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_dpp_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_ood_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_dpp_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_ood_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_dpp_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_ood_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_dpp_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_dpp_0.6_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/mrpc/0.0/ddpp_ood_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/mrpc/0.0/ddpp_ood_0.6_50'

HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_dpp_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_ood_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_dpp_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_ood_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_dpp_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_ood_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_dpp_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_dpp_0.6_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/cola/0.0/ddpp_ood_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/cola/0.0/ddpp_ood_0.6_50'

HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_dpp_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_ood_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_dpp_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_ood_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_dpp_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_ood_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_dpp_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_dpp_0.6_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/sst2/0.0/ddpp_ood_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/sst2/0.0/ddpp_ood_0.6_50'


HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_dpp_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.3_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_ood_0.3_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_dpp_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.4_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_ood_0.4_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_dpp_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.5_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_ood_0.5_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_dpp_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_dpp_0.6_50'
HYDRA_CONFIG_PATH=../configs/run_calc_ues_metrics.yaml python ./run_calc_ues_metrics_ner.py runs_dir='../workdir/run_glue_for_model_series/distilbert_raw/conll2003/0.0/ddpp_ood_0.6_50' output_dir='../workdir/run_calc_ues_metrics/distilbert_raw/conll2003/0.0/ddpp_ood_0.6_50'

