cd ../../src
# Script for training all models on MRPC, COLA, SST2-10%
# Last
# train
# Firstly run test on mrpc - is hypopt working
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=1.0 +ue.margin\=5.0 +ue.lamb_intra\=0.1 ue.reg_type\=metric +training.save_strategy\=no' task_configs=mrpc.yaml output_dir=../workdir/run_train_models/metric_electra_hypopt_params/mrpc/metric


HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.006 +ue.margin\=0.025 +ue.lamb_intra\=0.05 ue.reg_type\=metric +training.save_strategy\=no' task_configs=cola.yaml output_dir=../workdir/run_train_models/metric_electra_hypopt_params/cola/metric

HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.008 +ue.margin\=0.25 +ue.lamb_intra\=0.01 ue.reg_type\=metric +training.save_strategy\=no' task_configs=sst2.yaml output_dir=../workdir/run_train_models/metric_electra_hypopt_params/sst2/metric
# CONLL
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_conll2003_with_hyp_search.py task_configs=conll2003.yaml args='ue\=mc do_ue_estimate\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1 ue.reg_type\=metric ue.use_selective\=True ue.lamb\=0.1 ue.margin\=0.25 ue.lamb_intra\=2.5 +training.save_strategy\=no' seeds=[23419] cuda_devices=[0] output_dir='../workdir/run_train_models/metric_electra_hypopt_params/conll/metric'

# train - metric loss, SN
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.01 +ue.margin\=0.25 +ue.lamb_intra\=2.5 ue.reg_type\=metric +ue.use_spectralnorm\=True spectralnorm_layer\=last +training.save_strategy\=no' task_configs=mrpc.yaml output_dir=../workdir/run_train_models/metric_electra_hypopt_params/mrpc/metric_sn
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.006 +ue.margin\=0.5 +ue.lamb_intra\=2.5 ue.reg_type\=metric +ue.use_spectralnorm\=True spectralnorm_layer\=last +training.save_strategy\=no' task_configs=cola.yaml output_dir=../workdir/run_train_models/metric_electra_hypopt_params/cola/metric_sn
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_glue_with_hyp_search.py cuda_devices=[0] seeds=[23419] args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=True data.validation_subsample\=0.0 training\=electra_base ue.dropout_subs\=last ue.lamb\=0.006 +ue.margin\=5.0 +ue.lamb_intra\=0.01 ue.reg_type\=metric +ue.use_spectralnorm\=True spectralnorm_layer\=last +training.save_strategy\=no' task_configs=sst2.yaml output_dir=../workdir/run_train_models/metric_electra_hypopt_params/sst2/metric_sn
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py script=run_conll2003_with_hyp_search.py task_configs=conll2003.yaml args='ue\=mc do_ue_estimate\=False data.subsample_perc_val\=0.1 data.subsample_perc\=0.1 ue.reg_type\=metric ue.use_selective\=True ue.lamb\=0.1 ue.margin\=0.5 ue.lamb_intra\=0.025 +ue.use_spectralnorm\=True +spectralnorm_layer\=last +training.save_strategy\=no' seeds=[23419] cuda_devices=[0] output_dir='../workdir/run_train_models/metric_electra_hypopt_params/conll/metric_sn'