cd ../../src
#CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/clinc.yaml python ./run_ood_with_hyp_search.py ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=False training\=electra_base hydra.run.dir=../workdir/hp_search/electra_raw_no_sn/clinc model.model_name_or_path='google/electra-base-discriminator' &
#CUDA_VISIBLE_DEVICES=1 HYDRA_CONFIG_PATH=../configs/clinc.yaml python ./run_ood_with_hyp_search.py ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=True training\=electra_base hydra.run.dir=../workdir/hp_search/electra_raw_sn/clinc model.model_name_or_path='google/electra-base-discriminator' &
#CUDA_VISIBLE_DEVICES=2 HYDRA_CONFIG_PATH=../configs/rostd.yaml python ./run_ood_with_hyp_search.py ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=False training\=electra_base hydra.run.dir=../workdir/hp_search/electra_raw_no_sn/rostd model.model_name_or_path='google/electra-base-discriminator'
#wait
#CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG_PATH=../configs/rostd.yaml python ./run_ood_with_hyp_search.py ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=True training\=electra_base hydra.run.dir=../workdir/hp_search/electra_raw_sn/rostd model.model_name_or_path='google/electra-base-discriminator' &
CUDA_VISIBLE_DEVICES=1 HYDRA_CONFIG_PATH=../configs/snips.yaml python ./run_ood_with_hyp_search.py ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=False training\=electra_base hydra.run.dir=../workdir/hp_search/electra_raw_no_sn/snips model.model_name_or_path='google/electra-base-discriminator' &
CUDA_VISIBLE_DEVICES=2 HYDRA_CONFIG_PATH=../configs/snips.yaml python ./run_ood_with_hyp_search.py ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.reg_type\=raw +ue.use_spectralnorm\=True training\=electra_base hydra.run.dir=../workdir/hp_search/electra_raw_sn/snips model.model_name_or_path='google/electra-base-discriminator'
wait
