cd ../../src
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.calibrate\=False ue.reg_type\=raw +ue.use_spectralnorm\=False training\=electra_base training.num_train_epochs\=7 training.learning_rate\=7e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0.01 +ue.margin\=0.025 +ue.lamb_intra\=0.2 ue.lamb\=1.0' task_configs=clinc.yaml output_dir=../workdir/run_train_models/electra_raw_no_sn/clinc/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.calibrate\=False ue.reg_type\=raw +ue.use_spectralnorm\=True training\=electra_base training.num_train_epochs\=12 training.learning_rate\=0.0001 training.per_device_train_batch_size\=64 +training.weight_decay\=0 +ue.margin\=0.1 +ue.lamb_intra\=0.003 ue.lamb\=0.01' task_configs=clinc.yaml output_dir=../workdir/run_train_models/electra_raw_sn/clinc/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=False ue.reg_type\=reg-curr +ue.use_spectralnorm\=False training\=electra_base training.num_train_epochs\=8 training.learning_rate\=0.0001 training.per_device_train_batch_size\=64 +training.weight_decay\=0.01 +ue.margin\=0.05 +ue.lamb_intra\=0.002 ue.lamb\=0.001' task_configs=clinc.yaml output_dir=../workdir/run_train_models/electra_reg_no_sn/clinc/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=False ue.reg_type\=reg-curr +ue.use_spectralnorm\=True training\=electra_base training.num_train_epochs\=10 training.learning_rate\=5e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0.01 +ue.margin\=0.05 +ue.lamb_intra\=0.006 ue.lamb\=0.01' task_configs=clinc.yaml output_dir=../workdir/run_train_models/electra_reg_sn/clinc/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.calibrate\=False ue.reg_type\=raw +ue.use_spectralnorm\=False training\=electra_base training.num_train_epochs\=8 training.learning_rate\=5e-06 training.per_device_train_batch_size\=16 +training.weight_decay\=0.01 +ue.margin\=10.0 +ue.lamb_intra\=0.008 ue.lamb\=0.008' task_configs=rostd.yaml output_dir=../workdir/run_train_models/electra_raw_no_sn/rostd/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=False ue.calibrate\=False ue.reg_type\=raw +ue.use_spectralnorm\=True training\=electra_base training.num_train_epochs\=7 training.learning_rate\=7e-06 training.per_device_train_batch_size\=16 +training.weight_decay\=0.1 +ue.margin\=5.0 +ue.lamb_intra\=0.006 ue.lamb\=0.002' task_configs=rostd.yaml output_dir=../workdir/run_train_models/electra_raw_sn/rostd/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=False ue.reg_type\=metric +ue.use_spectralnorm\=False training\=electra_base training.num_train_epochs\=9 training.learning_rate\=0.0001 training.per_device_train_batch_size\=64 +training.weight_decay\=0 +ue.margin\=10.0 +ue.lamb_intra\=0.002 ue.lamb\=0.1' task_configs=rostd.yaml output_dir=../workdir/run_train_models/electra_metric_no_sn/rostd/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=False ue.reg_type\=metric +ue.use_spectralnorm\=True training\=electra_base training.num_train_epochs\=4 training.learning_rate\=2e-05 training.per_device_train_batch_size\=8 +training.weight_decay\=0.1 +ue.margin\=5.0 +ue.lamb_intra\=0.1 ue.lamb\=0.003' task_configs=rostd.yaml output_dir=../workdir/run_train_models/electra_metric_sn/rostd/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=False ue.reg_type\=reg-curr +ue.use_spectralnorm\=False training\=electra_base training.num_train_epochs\=5 training.learning_rate\=1e-05 training.per_device_train_batch_size\=8 +training.weight_decay\=0 +ue.margin\=0.1 +ue.lamb_intra\=0.05 ue.lamb\=0.2' task_configs=rostd.yaml output_dir=../workdir/run_train_models/electra_reg_no_sn/rostd/
HYDRA_CONFIG_PATH=../configs/run_train_models.yaml python ./run_train_models.py cuda_devices=[0,1,2] script=run_ood.py args='ue\=mc do_ue_estimate\=False ue.use_selective\=True ue.calibrate\=False ue.reg_type\=reg-curr +ue.use_spectralnorm\=True training\=electra_base training.num_train_epochs\=6 training.learning_rate\=7e-06 training.per_device_train_batch_size\=16 +training.weight_decay\=0.1 +ue.margin\=0.5 +ue.lamb_intra\=0.05 ue.lamb\=0.02' task_configs=rostd.yaml output_dir=../workdir/run_train_models/electra_reg_sn/rostd/